### ISSUE TITLE
Endless loading when logout in new tab

### ISSUE THREAD

**Issue by Xwilarg** [maximelouet/blih-web#1]
Hi,

I noticed an issue if I click in the 'Logout' button while pressing the Control key to open it in a new tab.
The issue does not occur when I do a right click, then 'Open in a new tab'.

**Comment by maximelouet** [comment]
Hi !
Thank you for your report. I consider this as an important problem.
I was able to resolve this issue by changing the logout link to a button. It is no longer possible to open it in a new tab, and Control+click just acts like a simple click.
If you have other problems to report, feel free to open another issue !
