### ISSUE TITLE
Add clone command in the interface

### ISSUE THREAD

**Issue by linsesh** [maximelouet/blih-web#5]
It would be useful to add a "clone" button when browsing repositories. 
It could be coupled with a system allowing to manage ssh keys

**Comment by maximelouet** [comment]
Unfortunately, cloning directly from BLIH Web requires that the user uploads my own SSH key to their BLIH account, granting me write-access to all of their repositories. This is a huge security risk.

About SSH keys management, this feature is a work-in-progress, almost finished! Stay tuned :)

**Comment by linsesh** [comment]
You simply could ask the user for his ssh key and then delete it ? Or is it considered too risky ?

**Comment by maximelouet** [comment]
I could ask the user for their private SSH key, clone the repo, and then delete it. But that means that their private SSH key would be stored on my server (even temporarily). I consider this insecure.
Actually, passwords are never transmitted to my server. Only SHA512 hashes of a mix of username, password, and other data goes through my server.

I could put a "copy clone command" button on repositories, which copies the "git clone git@git.epitech.eu:/user/repo" string. What do you think? Would it be useful?

**Comment by linsesh** [comment]
It wouldn't be useful according to me.
Why not grant read access to yourself and simply clone the repo ?

**Comment by maximelouet** [comment]
Well, yes, I could add read permissions for my username, clone the repo, and remove read permissions for my username.
That would really be a lot of work... 
I currently don't plan to do this, although it may be a candidate for BLIH Web 3.0 !

**Comment by linsesh** [comment]
Would be great !
