### ISSUE TITLE
Can't login if no repository

### ISSUE THREAD

**Issue by Xwilarg** [maximelouet/blih-web#6]
Hi,

If you try to login while having no repository it will fail displaying a red popup "No repositories"

That's a bit annoying because it means you can't create new repositories using Blih web or manage your SSH keys.

**Comment by maximelouet** [comment]
Hi,
Thank you for your report. I never tested BLIH Web with no repositories and this error makes sense.
Do you know the HTTP response code from BLIH when trying to log in in this case?
