### ISSUE TITLE
No error message when the intranet is down

### ISSUE THREAD

**Issue by AnastasiaPromtep** [maximelouet/blih-web#8]
When creating a repository while the intranet is down, the red error box is empty.

**Comment by maximelouet** [comment]
Thank you. This seems to be caused by an HTTP 504 (Gateway Timeout) from the BLIH API.
This error is not handled on the client side and therefore displays no message.
I'll work on this soon.

**Comment by maximelouet** [comment]
This issue was caused by a low timeout in my reverse proxy. I just fixed this, and now the BLIH Website at blih.saumon.io is displaying an error message.
Please note that there were no issues in the BLIH Web code, the issue was only on my personal server.
